[package]
name = "slimedb"
version = "0.1.0"
edition = "2021"
authors = ["r-cha"]
license = "MIT"
repository = "https://github.com/r-cha/slimedb"
description = "A simple, useless, and questionable database in Rust."
readme = "README.md"
keywords = ["database", "rust"]
